language: node_js

cache:
  directories:
    # cache yarn
    - $HOME/.cache/yarn

    # cache npm
    - $HOME/.npm
    - node_modules
    - $TRAVIS_BUILD_DIR/node_modules

    # cache parcel
    - $TRAVIS_BUILD_DIR/.cache

env:
  global:
    - secure: EbZ5DBFYSvf537k6pvY97tTnqp83Gv2jCMsgwRAyX7BGgk/bldc+UEIaAA/DXXVvNaKfqm9ejWZxDrR9V48w1LPTDbqy2d5lZjM6iG6M8znNPPURxY5ABWXm/wMN3PnFSgL6qOF1gf6QbbLUdVkxG9bgflwJcxFHNv+teYSlVkzKhhxm7Kr+dG23xWi5aHAKYE0eU2phsMu0XZa4XYAEJBeSyYEAApDdaZG15OJupzUKC3l0ef3bQ4aJOinszjnU+XRFJYdM43wND++UMP80s8s6l7uDSTP56m72APOVX+wiHGReAv5AKj8GXB/UOdDdeZ8lrNpD6uz20ncEzMPSfr4BlwiLGdXjn3oYO/qx98+aFJFYYqK1U8LCSMFa/BuVJMYW0hDMTYe1KiWOrkbFUuWjLwp4/EfPhnTmzaqbRJ72nG+NQqgE3YLmncqJ8THiqm2ymyf+pmyPvdAZrt5vVLrCZPxgvvumKU0vRaMHOFRDxUOKwLjFyVIBT6Y7PZP89euOBsEiy7Whk/bBcA8xoXxDUKfk3pnZe8dsgI2Ln3lyzpyfD7wbPb2MLuv560jay4ozhCCF2nBIWltraetVySvzwy5rWf3wjAO5SeP6YmHiaNH1gNVHXQINXgyRT1FsepLY3oGObJ9hin/cDk0zAei54QGsAFiBECemUpOZu50=
    - secure: ouqiyBUYXqbsF+YRd46rYjv1glaviu0xsuwhPHZZj9sWERTFdXWoIRMMnmgohNFIEbbwNeaye0PUe5/RLa+7j64qJhLQEph7/geoC/liTu4yeZVrtr37CEBTFeBmts8RrNPBhmb/928uobzqma85PJBM8q1yax1QguOKX/pgdeBHqHLxMqIkGqzBQb1u3fA2nzvf+RCl3ftcBI13LhsNakrKgSM7lX9h5quJV4hIGm0FkEFoboq/nLVXW0A9OQVuiC4Wfl48ZZB+acJmBXK4mb4A4rBV8dulThF1Hwuwrsi0/8I7ASh4xr2gVEwi7M6Nm0eX2jlbupOumPj5O/IbBFJDko1NsCAPhP83Ny7nH6Q71JChjXz0pPEV4sTxMhZOIDekjBDxeRq7PeUe3Bu/4Vu3mfahxTUzK2JXQGbqXjjwgmLsk2mHC3BzVRJd1+qmvaf5yintqZwXoOtP+Mte3TvHcQW/00Tt1t8RnBZsdF9mlAS25K7W4onbBlg+fgAlC2RFR01dS7eagCe2IPAfsJm1vBKZ77CSGjmYTbqJH5WZCXC1I/XNxUsAA2HyOXwIBfbDRTokUvEQP+JiXS7BNI32P0XxItzj0XAaXkSC0OvTSfubDg+S+Uy9WEoMQvU3CSkTDGNxr+buMwBw3jXMHe8U0cXjyJpzBUBIfZBGIyI=
    - secure: Lj3Q7hbBBTqIV8Uc9ASSbTH3YGDvAFi+2EqaYGekLrv2FkWQx6LQaiUY5aPsZCHvy6UHbuUhB0LG0VStrR1OVHiG9wjfKIX36UrseGNgOorpTHog4D5QK/eBlm7RtY+A79bxCgxv18DItaXhDKnC4GuU5sEg+HRhPL7Jz/UF2Olf2kvm7bEmiSkWz4ERZ1/VYdiGFMHU/JqY0AUyuFeEXh/2lCN6Tfz6IAJwfB+mma4IjfMUg5xZxUnrUVjjBcWo3MuVGM7WcMwLFh9xvaOVM7GvhnIz7Xna9OITUWWDSPyyOd1O1JUdgyRKIAsPe8w9GtvH0kptL00FTIQM37y1grBqkEq+p/RxtJcjXHAVmHHpOPZkYYHBtWg6ag7TS4JOA+A/GLtG+7ULvC13Nw5ymq4e2HjR8g1jSe2UWE9vUOAcGr5fdOz9luQgSAkkexU0CDEKfGAONReRhXQOHI1ziRO3OyxVqKYvuMzKah7fNSbAtil85lxVRHXkgD3KKIvFAE3I/TCd+Km4fXGXxbhNfDXqM/UaECmOukbbaiGoHz4HF7/u8KvarYaRvJDzHrbb93CyIwP4LbtfgYkQZYuym+V2IYLzzT12XglBSNrwcmxXK+/bHNbL/m+89qGKTJGguYXfKwbV0fhg+SNjJE4zTFnH+F1pLSPKvNWYlH6+W8M=

before_install:
  # get the right npm version
  - NPM_VERSION=`node -pe "require('./package.json').engines.npm"`
  - if [ `npm --version` != "$NPM_VERSION" ]; then
    npm install --global npm@${NPM_VERSION};
    fi

  # get the right yarn version
  - YARN_VERSION=`node -pe "require('./package.json').engines.yarn"`
  - if [ `yarn --version` != "$YARN_VERSION" ]; then
    curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION;
    export PATH=$HOME/.yarn/bin:$PATH;
    fi

before_script:
  # code climate's coverage reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - './cc-test-reporter before-build'

script:
  - yarn lint
  - yarn test
  - yarn build

after_success:
  - test $TRAVIS_PULL_REQUEST != "false" && npx semantic-release-github-pr

deploy:
  # deploy a git tag, release notes, bump package.json, update READMEs
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      branch: master

  # deploy the site
  - provider: pages
    repo: fartts/superfluity
    target_branch: gh-pages
    github_token: '$GH_TOKEN'
    allow_empty_commit: true
    skip_cleanup: true
    keep_history: true
    local_dir: dist/
    on:
      branch: master

after_script:
  # report coverage
  - './cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT'
